# Data cleansing

In [172]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os

%matplotlib inline
sns.set_style("dark")

In [173]:
!echo %cd%

E:\Courses\Mentalhealth_project\scripts

# Prepare codebook

In [174]:
data = pd.read_csv("../data/raw_data.csv", encoding='latin-1')
df = data.copy()
df.columns = ['C'+ str(i + 1) for i in range(len(df.columns))]
d = zip(data.columns,df.columns)
pd.options.display.max_rows = 65
codebook = pd.DataFrame([dict(d)]).T.reset_index().rename(columns = {"index":"Old_names",0:"New_names"})

if os.path.exists("../docs/Codebook.csv"):
    os.remove("../docs/Codebook.csv")
    
codebook.sort_values(by = ['New_names']).to_csv("../docs/Codebook.csv",index=False)

In [175]:
data.head()

,Unnamed: 0,Are.you.self.employed.,How.many.employees.does.your.company.or.organization.have.,Is.your.employer.primarily.a.tech.company.organization.,Is.your.primary.role.within.your.company.related.to.tech.IT.,Does.your.employer.provide.mental.health.benefits.as.part.of.healthcare.coverage.,Do.you.know.the.options.for.mental.health.care.available.under.your.employer.provided.coverage.,Has.your.employer.ever.formally.discussed.mental.health..for.example..as.part.of.a.wellness.campaign.or.other.official.communication..,Does.your.employer.offer.resources.to.learn.more.about.mental.health.concerns.and.options.for.seeking.help.,Is.your.anonymity.protected.if.you.choose.to.take.advantage.of.mental.health.or.substance.abuse.treatment.resources.provided.by.your.employer.,...,If.you.have.a.mental.health.issue..do.you.feel.that.it.interferes.with.your.work.when.being.treated.effectively.,If.you.have.a.mental.health.issue..do.you.feel.that.it.interferes.with.your.work.when.NOT.being.treated.effectively.,What.is.your.age.,What.is.your.gender.,What.country.do.you.live.in.,What.US.state.or.territory.do.you.live.in.,What.country.do.you.work.in.,What.US.state.or.territory.do.you.work.in.,Which.of.the.following.best.describes.your.work.position.,Do.you.work.remotely.
0,1,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,...,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
1,2,0,6-25,1.0,NaN,No,Yes,Yes,Yes,Yes,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
2,3,0,6-25,1.0,NaN,No,NaN,No,No,I don't know,...,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
3,4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
4,5,0,6-25,0.0,1.0,Yes,Yes,No,No,No,...,Sometimes,Sometimes,43,Female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes

In [176]:
df.columns = ['C'+ str(i + 1) for i in range(len(data.columns))]
df.head()

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,...,C55,C56,C57,C58,C59,C60,C61,C62,C63,C64
0,1,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,...,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
1,2,0,6-25,1.0,NaN,No,Yes,Yes,Yes,Yes,...,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
2,3,0,6-25,1.0,NaN,No,NaN,No,No,I don't know,...,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
3,4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
4,5,0,6-25,0.0,1.0,Yes,Yes,No,No,No,...,Sometimes,Sometimes,43,Female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes

In [177]:
cb = pd.read_csv("../docs/Codebook.csv", encoding='latin-1')
cb

                                            Old_names New_names
0                                          Unnamed: 0        C1
1   Is.your.anonymity.protected.if.you.choose.to.t...       C10
2   If.a.mental.health.issue.prompted.you.to.reque...       C11
3   Do.you.think.that.discussing.a.mental.health.d...       C12
4   Do.you.think.that.discussing.a.physical.health...       C13
5   Would.you.feel.comfortable.discussing.a.mental...       C14
6   Would.you.feel.comfortable.discussing.a.mental...       C15
7   Do.you.feel.that.your.employer.takes.mental.he...       C16
8   Have.you.heard.of.or.observed.negative.consequ...       C17
9   Do.you.have.medical.coverage..private.insuranc...       C18
10  Do.you.know.local.or.online.resources.to.seek....       C19
11                             Are.you.self.employed.        C2
12  If.you.have.been.diagnosed.or.treated.for.a.me...       C20
13  If.you.have.revealed.a.mental.health.issue.to....       C21
14  If.you.have.been.diagnosed.or.treated.for.a.me...       C22
15  If.you.have.revealed.a.mental.health.issue.to....       C23
16  Do.you.believe.your.productivity.is.ever.affec...       C24
17  If.yes..what.percentage.of.your.work.time..tim...       C25
18                    Do.you.have.previous.employers.       C26
19  Have.your.previous.employers.provided.mental.h...       C27
20  Were.you.aware.of.the.options.for.mental.healt...       C28
21  Did.your.previous.employers.ever.formally.disc...       C29
22  How.many.employees.does.your.company.or.organi...        C3
23  Did.your.previous.employers.provide.resources....       C30
24  Was.your.anonymity.protected.if.you.chose.to.t...       C31
25  Do.you.think.that.discussing.a.mental.health.d...       C32
26  Do.you.think.that.discussing.a.physical.health...       C33
27  Would.you.have.been.willing.to.discuss.a.menta...       C34
28  Would.you.have.been.willing.to.discuss.a.menta...       C35
29  Did.you.feel.that.your.previous.employers.took...       C36
30  Did.you.hear.of.or.observe.negative.consequenc...       C37
31  Would.you.be.willing.to.bring.up.a.physical.he...       C38
32                                    Why.or.why.not.       C39
33  Is.your.employer.primarily.a.tech.company.orga...        C4
34  Would.you.bring.up.a.mental.health.issue.with....       C40
35                                  Why.or.why.not..1       C41
36  Do.you.feel.that.being.identified.as.a.person....       C42
37  Do.you.think.that.team.members.co.workers.woul...       C43
38  How.willing.would.you.be.to.share.with.friends...       C44
39  Have.you.observed.or.experienced.an.unsupporti...       C45
40  Have.your.observations.of.how.another.individu...       C46
41    Do.you.have.a.family.history.of.mental.illness.       C47
42  Have.you.had.a.mental.health.disorder.in.the.p...       C48
43    Do.you.currently.have.a.mental.health.disorder.       C49
44  Is.your.primary.role.within.your.company.relat...        C5
45  If.yes..what.condition.s..have.you.been.diagno...       C50
46  If.maybe..what.condition.s..do.you.believe.you...       C51
47  Have.you.been.diagnosed.with.a.mental.health.c...       C52
48  If.so..what.condition.s..were.you.diagnosed.with.       C53
49  Have.you.ever.sought.treatment.for.a.mental.he...       C54
50  If.you.have.a.mental.health.issue..do.you.feel...       C55
51  If.you.have.a.mental.health.issue..do.you.feel...       C56
52                                  What.is.your.age.       C57
53                               What.is.your.gender.       C58
54                       What.country.do.you.live.in.       C59
55  Does.your.employer.provide.mental.health.benef...        C6
56         What.US.state.or.territory.do.you.live.in.       C60
57                       What.country.do.you.work.in.       C61
58         What.US.state.or.territory.do.you.work.in.       C62
59  Which.of.the.following.best.describes.your.wor...       C63
60                              Do.you.work.remotely.       C64
61  Do.you.know.the.options.for.mental.health.care...        C7
62  Has.your.employer.ever.formally.discussed.ment...        C8
63  Does.your.employer.offer.resources.to.learn.mo...        C9

# Cleansing data

### Classifying gender into 3 groups for ease of analysis - Male, Female and NB

In [178]:
df.C58.unique()

array(['Male', 'male', 'Male ', 'Female', 'M', 'female', 'm',
       'I identify as female.', 'female ', 'Bigender', 'non-binary',
       'Female assigned at birth ', 'F', 'Woman', 'man', 'fm', 'f',
       'Cis female ', 'Transitioned, M2F', 'Genderfluid (born female)',
       'Other/Transfeminine', 'Female or Multi-Gender Femme', 'Female ',
       'woman', 'female/woman', 'Cis male', 'Male.', 'Androgynous',
       'male 9:1 female, roughly', nan, 'Male (cis)', 'Other',
       'nb masculine', 'Cisgender Female', 'Man', 'Sex is male',
       'none of your business', 'genderqueer', 'cis male', 'Human',
       'Genderfluid', 'Enby', 'Malr', 'genderqueer woman', 'mtf', 'Queer',
       'Agender', 'Dude', 'Fluid',
       "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? ",
       'mail', 'M|', 'Male/genderqueer', 'fem', 'Nonbinary', 'male ',
       'human', 'Female (props for making this a freeform field, though)',
       ' Female', 'Unicorn', 'Cis Male', 'Male (trans, FtM)', 'Cis-woman',
       'Genderqueer', 'cisdude', 'Genderflux demi-girl',
       'female-bodied; no feelings about gender', 'cis man', 'AFAB',
       'Transgender woman', 'MALE'], dtype=object)

In [179]:
# clean the genders by grouping the genders into 3 categories: Female, Male, Genderqueer/Other
# sourced from https://www.kaggle.com/jchen2186/data-visualization-with-python-seaborn

df['C58'] = df['C58'].replace([
    'male', 'Male ', 'M', 'm', 'man', 'Cis male',
    'Male.', 'Male (cis)', 'Man', 'Sex is male',
    'cis male', 'Malr', 'Dude', "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? ",
    'mail', 'M|', 'male ', 'Cis Male', 'Male (trans, FtM)',
    'cisdude', 'cis man', 'MALE'], 'Male')
df['C58'] = df['C58'].replace([
    'female', 'I identify as female.', 'female ',
    'Female assigned at birth ', 'F', 'Woman', 'fm', 'f',
    'Cis female', 'Transitioned, M2F', 'Female or Multi-Gender Femme',
    'Female ', 'woman', 'female/woman', 'Cisgender Female', 
    'mtf', 'fem', 'Female (props for making this a freeform field, though)',
    ' Female', 'Cis-woman', 'AFAB', 'Transgender woman',
    'Cis female '], 'Female')
df['C58'] = df['C58'].replace([
    'Bigender', 'non-binary,', 'Genderfluid (born female)',
    'Other/Transfeminine', 'Androgynous', 'male 9:1 female, roughly',
    'nb masculine', 'genderqueer', 'Human', 'Genderfluid',
    'Enby', 'genderqueer woman', 'Queer', 'Agender', 'Fluid',
    'Genderflux demi-girl', 'female-bodied; no feelings about gender',
    'non-binary', 'Male/genderqueer', 'Nonbinary', 'Other', 'none of your business',
    'Unicorn', 'human', 'Genderqueer'], 'Non-binary')

# replace the one null with Male, the mode gender, so we don't have to drop the row
df['C58'] = df['C58'].replace(np.NaN, 'Male')

### Removing self employed professionals from analysis for tech companies

In [180]:
#Removing self employed professionals for the sake of this analysis
df = df.query('C2 == 0')

In [181]:
a = df.applymap(np.isreal).all()

In [182]:
df.iloc[:,-np.where(a)[0]].head()

,C1,C64,C62,C61,C48,C47,C46,C45,C44,C43,C42,C41,C40,C12,C9
0,1,Sometimes,NaN,United Kingdom,Yes,No,NaN,No,Somewhat open,"No, I don't think they would",Maybe,NaN,Maybe,No,No
1,2,Never,Illinois,United States of America,Yes,Yes,NaN,No,Somewhat open,"No, I don't think they would","No, I don't think it would",While mental health has become a more prominen...,No,No,Yes
2,3,Always,NaN,United Kingdom,Maybe,No,Yes,Maybe/Not sure,Somewhat open,Maybe,Maybe,"Stigma, mainly.",Yes,Maybe,No
4,5,Sometimes,Illinois,United States of America,Yes,Yes,Yes,"Yes, I experienced",Somewhat open,Maybe,"Yes, I think it would",I don't know,No,Yes,No
5,6,Sometimes,NaN,United Kingdom,No,No,No,"Yes, I experienced",Somewhat open,Maybe,"Yes, I think it would",It would depend on the field & what I knew of ...,Maybe,Yes,Yes

# Summary tables

In [183]:
df.describe(include = [np.object])

,C3,C6,C7,C8,C9,C10,C11,C12,C13,C14,...,C53,C55,C56,C58,C59,C60,C61,C62,C63,C64
count,1146,1146,1013,1146,1146,1146,1146,1146,1146,1146,...,563,1146,1146,1146,1146,709,1146,716,1146,1146
unique,6,4,3,3,3,3,6,3,3,3,...,90,5,5,3,43,47,44,48,180,3
top,26-100,Yes,No,No,No,I don't know,Somewhat easy,Maybe,No,Maybe,...,"Mood Disorder (Depression, Bipolar Disorder, etc)",Not applicable to me,Often,Male,United States of America,California,United States of America,California,Back-end Developer,Sometimes
freq,292,531,354,813,531,742,281,487,837,479,...,151,455,422,850,709,110,716,120,238,611

In [184]:
df.describe(include = [np.number])

,C1,C2,C4,C5,C18,C26,C54,C57
count,1146.000000,1146.0,1146.000000,263.000000,0.0,1146.000000,1146.000000,1146.000000
mean,708.903141,0.0,0.770506,0.942966,NaN,0.885689,0.573298,33.655323
std,419.119547,0.0,0.420691,0.232350,NaN,0.318327,0.494814,11.703277
min,1.000000,0.0,0.000000,0.000000,NaN,0.000000,0.000000,3.000000
25%,339.250000,0.0,1.000000,1.000000,NaN,1.000000,0.000000,28.000000
50%,690.500000,0.0,1.000000,1.000000,NaN,1.000000,1.000000,32.000000
75%,1079.500000,0.0,1.000000,1.000000,NaN,1.000000,1.000000,38.000000
max,1433.000000,0.0,1.000000,1.000000,NaN,1.000000,1.000000,323.000000

# Write cleansed data to file

In [185]:
df.to_csv("../data/cleansed_data.csv")